name: Food KG metadata Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-jsonld:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyshacl

    - name: Extract JSON-LD from docs/index.html
      run: |
        echo "🔍 Extracting JSON-LD from docs/index.html"
        python3 docs/extract_jsonld.py

    - name: Run SHACL Validation
      run: |
        echo "🧪 Validating docs/extracted.jsonld against docs/jsonld-shacl.ttl"
        python3 docs/validate.py -d docs/extracted.jsonld -s docs/jsonld-shacl.ttl
