name: Validate HTML and JSON-LD

on:
  push:
    paths:
      - 'index.html'
  pull_request:
    paths:
      - 'index.html'

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install htmlhint
      run: npm install -g htmlhint

    - name: Validate HTML syntax
      run: htmlhint index.html

    - name: Validate embedded JSON-LD
      run: |
        python3 -c "import re, json
with open('index.html') as f:
    html = f.read()
match = re.search(r'<script type=\"application/ld\\+json\">(.*?)</script>', html, re.DOTALL)
if not match:
    raise ValueError('No JSON-LD block found')
json_text = match.group(1).strip()
json.loads(json_text)
print('✅ JSON-LD is valid')"
