- name: Validate embedded JSON-LD
  run: |
    cat << EOF > validate_jsonld.py
import re, json

with open('index.html') as f:
    html = f.read()

match = re.search(r'<script type="application/ld\\+json">(.*?)</script>', html, re.DOTALL)
if not match:
    raise ValueError('No JSON-LD block found')

json_text = match.group(1).strip()
json.loads(json_text)
print('✅ JSON-LD is valid')
EOF
    python3 validate_jsonld.py
