name: Validate HTML and JSON-LD

on:
  push:
    paths:
      - 'index.html'
  pull_request:
    paths:
      - 'index.html'

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Initialize Node project and install deps
        run: |
          npm init -y
          npm install cheerio
          npm install -g htmlhint jsonlint

      - name: Validate HTML syntax
        run: htmlhint index.html

      - name: Extract JSON-LD using cheerio
        run: |
          echo "const fs = require('fs');
          const cheerio = require('cheerio');
          const html = fs.readFileSync('index.html', 'utf-8');
          const \$ = cheerio.load(html);
          const jsonld = \$('script[type=\"application/ld+json\"]').first().html();
          if (!jsonld) {
            console.error('No JSON-LD block found.');
            process.exit(1);
          }
          fs.writeFileSync('extracted.json', jsonld);" > extract.js
          node extract.js

      - name: Validate JSON-LD syntax
        run: jsonlint extracted.json
